module.exports={
    mode:"production",
    entry:{
        client:"./client/client.jsx"
    },
    output:{
        filename:'[name].js'
    },
    resolve:{
        extensions:['.js','.jsx']
    },
    module:{
        rules:[{
            test:/\.jsx?$/,
            exclude:/(node_modules)/,
            use:{
                loader:'babel-loader',
                options:{
                    presets:[
                        "@babel/preset-env",
                        "@babel/preset-react"
                    ]
                }
            }
        }]
    }
}
